# numpy examples

In [1]:
import sys
import numpy as np

In [2]:
data = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [20, 30, 40]]

In [3]:
a = np.array(data)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [20, 30, 40]])

In [4]:
a.ndim

2

In [5]:
a.shape

(4, 3)

In [6]:
a.size

12

In [7]:
a.itemsize

8

In [9]:
a.nbytes

96

In [10]:
a_zeros = np.zeros((10, 3), dtype=np.uint32)
a_zeros

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=uint32)

In [14]:
a_ones = np.ones((26,4))
a_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
a_empty  = np.empty((12, 2))
a_empty

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
a_nan = np.full((30, 5), 42)
a_nan

array([[42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42]])

In [18]:
a1 = np.arange(50)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [19]:
len(a1)

50

In [20]:
a1.shape

(50,)

In [21]:
a2 = np.arange(5, 101, 5)
a2

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [22]:
a3 = np.arange(1.0, 5.0, .2)
a3

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8])

In [25]:
a4 = np.linspace(0, 100, 25)
a4

array([  0.        ,   4.16666667,   8.33333333,  12.5       ,
        16.66666667,  20.83333333,  25.        ,  29.16666667,
        33.33333333,  37.5       ,  41.66666667,  45.83333333,
        50.        ,  54.16666667,  58.33333333,  62.5       ,
        66.66666667,  70.83333333,  75.        ,  79.16666667,
        83.33333333,  87.5       ,  91.66666667,  95.83333333,
       100.        ])

In [26]:
a = np.array(
      [
[5, 10, 15], [2, 4, 6], [3, 6, 9, ],
      ]
  )  # create 2D array
a

array([[ 5, 10, 15],
       [ 2,  4,  6],
       [ 3,  6,  9]])

In [28]:
b = np.array(
      [
[10, 85, 92], [77, 16, 14], [19, 52, 23],
      ]
  )
b

array([[10, 85, 92],
       [77, 16, 14],
       [19, 52, 23]])

In [29]:
a * 5

array([[25, 50, 75],
       [10, 20, 30],
       [15, 30, 45]])

In [30]:
a_times_5 = a * 5
a_times_5

array([[25, 50, 75],
       [10, 20, 30],
       [15, 30, 45]])

In [31]:
a

array([[ 5, 10, 15],
       [ 2,  4,  6],
       [ 3,  6,  9]])

In [32]:
b

array([[10, 85, 92],
       [77, 16, 14],
       [19, 52, 23]])

In [33]:
a + b

array([[ 15,  95, 107],
       [ 79,  20,  20],
       [ 22,  58,  32]])

In [34]:
def c2f(c):
    return (95 * c) + 32

In [35]:
c2f(a)

array([[ 507,  982, 1457],
       [ 222,  412,  602],
       [ 317,  602,  887]])

In [36]:
a

array([[ 5, 10, 15],
       [ 2,  4,  6],
       [ 3,  6,  9]])

In [37]:
a / 10

array([[0.5, 1. , 1.5],
       [0.2, 0.4, 0.6],
       [0.3, 0.6, 0.9]])

In [38]:
a

array([[ 5, 10, 15],
       [ 2,  4,  6],
       [ 3,  6,  9]])

In [39]:
a /= 10

UFuncTypeError: Cannot cast ufunc 'divide' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [40]:
a //= 10
a

array([[0, 1, 1],
       [0, 0, 0],
       [0, 0, 0]])

In [41]:
a += 25

In [42]:
a

array([[25, 26, 26],
       [25, 25, 25],
       [25, 25, 25]])

In [44]:
aa = np.arange(15)
aa

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [45]:
aa.shape

(15,)

In [47]:
aa.shape = (5, 3)
aa

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [48]:
aa.shape = (3, 5)
aa

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [49]:
aa.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [50]:
aa.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [51]:
r = aa.ravel()
r[0] = 99
aa

array([[99,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [52]:
f = aa.flatten()
f[0] = 1234
aa

array([[99,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [53]:
aa

array([[99,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [54]:
aa.transpose()

array([[99,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [55]:
a = np.array(
[[70, 31, 21, 76, 19, 5, 54, 66],
[23, 29, 71, 12, 27, 74, 65, 73], [11, 84, 7, 10, 31, 50, 11, 98], [25, 13, 43, 1, 31, 52, 41, 90], [75, 37, 11, 62, 35, 76, 38, 4]]
  ) 
a

array([[70, 31, 21, 76, 19,  5, 54, 66],
       [23, 29, 71, 12, 27, 74, 65, 73],
       [11, 84,  7, 10, 31, 50, 11, 98],
       [25, 13, 43,  1, 31, 52, 41, 90],
       [75, 37, 11, 62, 35, 76, 38,  4]])

In [56]:
a[0]

array([70, 31, 21, 76, 19,  5, 54, 66])

In [57]:
a[0][0]

70

In [58]:
a[0,0]

70

In [59]:
a[0,:3]

array([70, 31, 21])

In [60]:
a[:3,:2]

array([[70, 31],
       [23, 29],
       [11, 84]])

In [61]:
a[-3:,-2:]

array([[11, 98],
       [41, 90],
       [38,  4]])

In [62]:
# ARRAY[row-index,col-index]

In [64]:
a[:,:2]

array([[70, 31],
       [23, 29],
       [11, 84],
       [25, 13],
       [75, 37]])

In [65]:
a = np.array(
[[70, 31, 21, 76, 19, 5, 54, 66],
[23, 29, 71, 12, 27, 74, 65, 73], [11, 84, 7, 10, 31, 50, 11, 98], [25, 13, 43, 1, 31, 52, 41, 90], [75, 37, 11, 62, 35, 76, 38, 4]]
  ) 
a

array([[70, 31, 21, 76, 19,  5, 54, 66],
       [23, 29, 71, 12, 27, 74, 65, 73],
       [11, 84,  7, 10, 31, 50, 11, 98],
       [25, 13, 43,  1, 31, 52, 41, 90],
       [75, 37, 11, 62, 35, 76, 38,  4]])

In [66]:
a > 50

array([[ True, False, False,  True, False, False,  True,  True],
       [False, False,  True, False, False,  True,  True,  True],
       [False,  True, False, False, False, False, False,  True],
       [False, False, False, False, False,  True, False,  True],
       [ True, False, False,  True, False,  True, False, False]])

In [67]:
a[a > 50]

array([70, 76, 54, 66, 71, 74, 65, 73, 84, 98, 52, 90, 75, 62, 76])

In [68]:
mask = a > 50
mask

array([[ True, False, False,  True, False, False,  True,  True],
       [False, False,  True, False, False,  True,  True,  True],
       [False,  True, False, False, False, False, False,  True],
       [False, False, False, False, False,  True, False,  True],
       [ True, False, False,  True, False,  True, False, False]])

In [69]:
a[mask] * .1

array([7. , 7.6, 5.4, 6.6, 7.1, 7.4, 6.5, 7.3, 8.4, 9.8, 5.2, 9. , 7.5,
       6.2, 7.6])

In [70]:
data = np.loadtxt('../DATA/columns_of_numbers.txt', skiprows=1)
data

array([[63., 51., 59., 61., 50.,  4.],
       [40., 66.,  9., 64., 63., 17.],
       [18., 23.,  2., 61.,  1.,  9.],
       ...,
       [26., 20., 54., 46., 38., 23.],
       [ 9.,  5., 59., 23.,  2., 26.],
       [46., 34., 25.,  8., 39., 34.]])

In [71]:
data[:5]

array([[63., 51., 59., 61., 50.,  4.],
       [40., 66.,  9., 64., 63., 17.],
       [18., 23.,  2., 61.,  1.,  9.],
       [29.,  8., 40., 59., 10., 26.],
       [54.,  9., 68.,  4., 16., 21.]])

In [72]:
data[-10:]

array([[33.,  8., 45.,  9.,  2.,  5.],
       [ 5., 22., 45., 49., 10., 37.],
       [18., 53.,  5., 28., 20., 27.],
       [24., 44., 30., 32.,  7., 18.],
       [33., 26., 14., 41.,  1., 37.],
       [10., 32., 18.,  5., 23.,  4.],
       [ 6., 37., 42., 20., 25., 25.],
       [26., 20., 54., 46., 38., 23.],
       [ 9.,  5., 59., 23.,  2., 26.],
       [46., 34., 25.,  8., 39., 34.]])

In [73]:
selected = data[
    (data[:,0] < 10)
    &
    (data[:,-1] > 35)
]
selected

array([[ 8., 49.,  2., 40., 50., 36.],
       [ 4., 49., 39., 50., 23., 39.],
       [ 6.,  7., 40., 56., 31., 38.],
       [ 6.,  1., 44., 55., 49., 36.],
       [ 5., 22., 45., 49., 10., 37.]])

In [74]:
len(selected)

5

In [75]:
a = np.array(
[[70, 31, 21, 76, 19, 5, 54, 66],
[23, 29, 71, 12, 27, 74, 65, 73]] )
a

array([[70, 31, 21, 76, 19,  5, 54, 66],
       [23, 29, 71, 12, 27, 74, 65, 73]])

In [76]:
b = np.array(
[[11, 84, 7, 10, 31, 50, 11, 98],
[25, 13, 43, 1, 31, 52, 41, 90]] )
b

array([[11, 84,  7, 10, 31, 50, 11, 98],
       [25, 13, 43,  1, 31, 52, 41, 90]])

In [77]:
np.vstack((a, b))

array([[70, 31, 21, 76, 19,  5, 54, 66],
       [23, 29, 71, 12, 27, 74, 65, 73],
       [11, 84,  7, 10, 31, 50, 11, 98],
       [25, 13, 43,  1, 31, 52, 41, 90]])

In [78]:
np.hstack((a, b))

array([[70, 31, 21, 76, 19,  5, 54, 66, 11, 84,  7, 10, 31, 50, 11, 98],
       [23, 29, 71, 12, 27, 74, 65, 73, 25, 13, 43,  1, 31, 52, 41, 90]])

In [79]:
a

array([[70, 31, 21, 76, 19,  5, 54, 66],
       [23, 29, 71, 12, 27, 74, 65, 73]])

In [80]:
sums = np.vstack((a, a[0] + a[1]))
sums

array([[ 70,  31,  21,  76,  19,   5,  54,  66],
       [ 23,  29,  71,  12,  27,  74,  65,  73],
       [ 93,  60,  92,  88,  46,  79, 119, 139]])

`a1 + a2` is really `np.add(a1, a2)`

In [81]:
a + b

array([[ 81, 115,  28,  86,  50,  55,  65, 164],
       [ 48,  42, 114,  13,  58, 126, 106, 163]])

In [82]:
np.add(a, b)

array([[ 81, 115,  28,  86,  50,  55,  65, 164],
       [ 48,  42, 114,  13,  58, 126, 106, 163]])

In [83]:
from scipy import fftpack as ff

In [84]:
np.info(ff.fft)

 fft(x, n=None, axis=-1, overwrite_x=False)

Return discrete Fourier transform of real or complex sequence.

The returned complex array contains ``y(0), y(1),..., y(n-1)``, where

``y(j) = (x * exp(-2*pi*sqrt(-1)*j*np.arange(n)/n)).sum()``.

Parameters
----------
x : array_like
    Array to Fourier transform.
n : int, optional
    Length of the Fourier transform. If ``n < x.shape[axis]``, `x` is
    truncated. If ``n > x.shape[axis]``, `x` is zero-padded. The
    default results in ``n = x.shape[axis]``.
axis : int, optional
    Axis along which the fft's are computed; the default is over the
    last axis (i.e., ``axis=-1``).
overwrite_x : bool, optional
    If True, the contents of `x` can be destroyed; the default is False.

Returns
-------
z : complex ndarray
    with the elements::

        [y(0),y(1),..,y(n/2),y(1-n/2),...,y(-1)]        if n is even
        [y(0),y(1),..,y((n-1)/2),y(-(n-1)/2),...,y(-1)]  if n is odd

    where::

        y(j) = sum[k=0..n-1] x[k] * exp(-sqrt(-1)

In [85]:
ff.fft?

Signature: ff.fft(x, n=None, axis=-1, overwrite_x=False)
Docstring:
Return discrete Fourier transform of real or complex sequence.

The returned complex array contains ``y(0), y(1),..., y(n-1)``, where

``y(j) = (x * exp(-2*pi*sqrt(-1)*j*np.arange(n)/n)).sum()``.

Parameters
----------
x : array_like
    Array to Fourier transform.
n : int, optional
    Length of the Fourier transform. If ``n < x.shape[axis]``, `x` is
    truncated. If ``n > x.shape[axis]``, `x` is zero-padded. The
    default results in ``n = x.shape[axis]``.
axis : int, optional
    Axis along which the fft's are computed; the default is over the
    last axis (i.e., ``axis=-1``).
overwrite_x : bool, optional
    If True, the contents of `x` can be destroyed; the default is False.

Returns
-------
z : complex ndarray
    with the elements::

        [y(0),y(1),..,y(n/2),y(1-n/2),...,y(-1)]        if n is even
        [y(0),y(1),..,y((n-1)/2),y(-(n-1)/2),...,y(-1)]  if n is odd

    where::

        y(j) = sum[k=0..n-

In [86]:
np.source(ff.fft)

In file: /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scipy/fftpack/_basic.py

def fft(x, n=None, axis=-1, overwrite_x=False):
    """
    Return discrete Fourier transform of real or complex sequence.

    The returned complex array contains ``y(0), y(1),..., y(n-1)``, where

    ``y(j) = (x * exp(-2*pi*sqrt(-1)*j*np.arange(n)/n)).sum()``.

    Parameters
    ----------
    x : array_like
        Array to Fourier transform.
    n : int, optional
        Length of the Fourier transform. If ``n < x.shape[axis]``, `x` is
        truncated. If ``n > x.shape[axis]``, `x` is zero-padded. The
        default results in ``n = x.shape[axis]``.
    axis : int, optional
        Axis along which the fft's are computed; the default is over the
        last axis (i.e., ``axis=-1``).
    overwrite_x : bool, optional
        If True, the contents of `x` can be destroyed; the default is False.

    Returns
    -------
    z : complex ndarray
        with the elements

In [89]:
np.lookfor('deviation')

Search results for 'deviation'
------------------------------
numpy.std
    Compute the standard deviation along the specified axis.
numpy.nanstd
    Compute the standard deviation along the specified axis, while
numpy.ma.std
    Returns the standard deviation of the array elements along given axis.
numpy.ma.anom
    Compute the anomalies (deviations from the arithmetic mean)
numpy.matrix.std
    Return the standard deviation of the array elements along the given axis.
numpy.chararray.std
    Returns the standard deviation of the array elements along given axis.
numpy.ma.MaskedArray.std
    Returns the standard deviation of the array elements along given axis.
numpy.ma.MaskedArray.anom
    Compute the anomalies (deviations from the arithmetic mean)
numpy.var
    Compute the variance along the specified axis.
numpy.nanvar
    Compute the variance along the specified axis, while ignoring NaNs.
numpy.ma.var
    Compute the variance along the specified axis.
numpy.matlib.randn
    Return a

In [92]:
import scipy as sp
sp.lookfor('skew')

Search results for 'skew'
-------------------------
numpy.histogram_bin_edges
    Function to calculate only the edges of the bins used by the `histogram`


/var/folders/p7/_ryqngjd3jn_ppndvnhdzqch0000gn/T/ipykernel_66568/414896514.py:2: DeprecationWarning: scipy.lookfor is deprecated and will be removed in SciPy 2.0.0, use numpy.lookfor instead
  sp.lookfor('skew')


In [93]:
a

array([[70, 31, 21, 76, 19,  5, 54, 66],
       [23, 29, 71, 12, 27, 74, 65, 73]])

In [94]:
for value in a.flat:
    print(value)

70
31
21
76
19
5
54
66
23
29
71
12
27
74
65
73


In [95]:
r1 = np.arange(45)
r1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [98]:
r2 = np.arange(45.)
r2

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44.])

In [100]:
r3 = np.arange(45, dtype=np.int16)
r3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44], dtype=int16)

In [101]:
r1.dtype, r2.dtype, r3.dtype

(dtype('int64'), dtype('float64'), dtype('int16'))

In [102]:
r1.nbytes, r2.nbytes, r3.nbytes

(360, 360, 90)

In [111]:
raw_data = [1., 2, 3, 4, 5392582985]
d = np.array(raw_data, dtype=np.int16)
d

/var/folders/p7/_ryqngjd3jn_ppndvnhdzqch0000gn/T/ipykernel_66568/1174149433.py:2: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 5392582985 to int16 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  d = np.array(raw_data, dtype=np.int16)


array([    1,     2,     3,     4, 18761], dtype=int16)

In [110]:
d.dtype

dtype('int16')

In [112]:
data

array([[63., 51., 59., 61., 50.,  4.],
       [40., 66.,  9., 64., 63., 17.],
       [18., 23.,  2., 61.,  1.,  9.],
       ...,
       [26., 20., 54., 46., 38., 23.],
       [ 9.,  5., 59., 23.,  2., 26.],
       [46., 34., 25.,  8., 39., 34.]])

In [114]:
data = np.loadtxt("../DATA/columns_of_numbers.txt", skiprows=1, dtype=np.int32)
data

array([[63, 51, 59, 61, 50,  4],
       [40, 66,  9, 64, 63, 17],
       [18, 23,  2, 61,  1,  9],
       ...,
       [26, 20, 54, 46, 38, 23],
       [ 9,  5, 59, 23,  2, 26],
       [46, 34, 25,  8, 39, 34]], dtype=int32)

In [115]:
new_data = data * 10
new_data

array([[630, 510, 590, 610, 500,  40],
       [400, 660,  90, 640, 630, 170],
       [180, 230,  20, 610,  10,  90],
       ...,
       [260, 200, 540, 460, 380, 230],
       [ 90,  50, 590, 230,  20, 260],
       [460, 340, 250,  80, 390, 340]], dtype=int32)

In [125]:
np.savetxt('newdata.txt', new_data, delimiter=",", fmt="%d")

In [126]:
!cat newdata.txt | head

630,510,590,610,500,40
400,660,90,640,630,170
180,230,20,610,10,90
290,80,400,590,100,260
540,90,680,40,160,210
450,190,420,530,480,160
460,370,290,530,680,80
360,320,220,580,100,100
650,140,460,680,610,130
130,620,100,530,320,210
